name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:  ${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd frontend_app  # Change to the folder containing package-lock.json
        npm ci
    - name: Build the project
      run: |
        cd frontend_app  # Again, make sure you're in the right directory
        npm run build --if-present
    - name: Run tests
      run: |
        cd xx  # And here too
        npm test
